# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: rdimensions 0.1.2 ruby lib

Gem::Specification.new do |s|
  s.name = "rdimensions"
  s.version = "0.1.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Scott Brickner"]
  s.date = "2014-07-23"
  s.description = "Rudimentary access to Dimensions Metadata"
  s.email = "scottb@brickner.net"
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".ruby-version",
    "README",
    "Rakefile",
    "VERSION",
    "lib/rdimensions.rb",
    "lib/rdimensions/categories.rb",
    "lib/rdimensions/connection.rb",
    "lib/rdimensions/context.rb",
    "lib/rdimensions/contexts.rb",
    "lib/rdimensions/data_sources.rb",
    "lib/rdimensions/document.rb",
    "lib/rdimensions/exceptions.rb",
    "lib/rdimensions/field.rb",
    "lib/rdimensions/label.rb",
    "lib/rdimensions/labeled_object.rb",
    "lib/rdimensions/language.rb",
    "lib/rdimensions/mdm_array.rb",
    "lib/rdimensions/mdm_class.rb",
    "lib/rdimensions/mdm_element.rb",
    "lib/rdimensions/mdm_node.rb",
    "lib/rdimensions/mdm_object.rb",
    "lib/rdimensions/reader.rb",
    "lib/rdimensions/variable.rb",
    "lib/rdimensions/variable_instance.rb",
    "rdimensions.gemspec",
    "spec/fixtures/P4550054.mdd",
    "spec/rdimensions/document_spec.rb",
    "spec/rdimensions/labeled_object_spec.rb",
    "spec/rdimensions/mdm_array_spec.rb",
    "spec/rdimensions/reader_spec.rb",
    "spec/rdimensions/variable_instance_spec.rb",
    "spec/rdimensions/variable_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/scottb/rdimensions"
  s.required_ruby_version = Gem::Requirement.new("> 1.8.1")
  s.rubygems_version = "2.2.0"
  s.summary = "Dimensions Metadata"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 1.4"])
    else
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 1.4"])
    end
  else
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 1.4"])
  end
end

